package com.adil.nsealerts;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Backs the 5 dashboard tabs. Two tabs (market news, announcements) read
 * from this same service's own AlertLogService; the other three read a
 * SIBLING Railway service's alert log from GitHub, since rs-momentum-strategy-
 * live, multibagger-screener, and the DarvasBox shadow-trade service each
 * persist their own state to their own branch/path and there's no shared
 * filesystem or database between services. Cross-branch reads are cached
 * briefly (60s) so opening the dashboard or switching tabs repeatedly
 * doesn't hammer the GitHub API.
 */
@RestController
public class DashboardDataController {

    private final AlertLogService alertLogService;
    private final GithubJsonStore githubJsonStore;
    private final QuarterlyResultsService quarterlyResultsService;
    private final RsRankLookupService rsRankLookupService;
    private final RsMomentumService rsMomentumService;
    private final SwingSignalService swingSignalService;
    private final SwingLivePriceService swingLivePriceService;
    private final CryptoForexService cryptoForexService;
    private final Map<String, CacheEntry> cache = new ConcurrentHashMap<>();
    private static final long CACHE_TTL_MS = 60_000;
    private final ObjectMapper mapper = new ObjectMapper();
    // Loaded once at startup, not per-request: unlike the other tabs this isn't a live
    // alert feed, it's a monthly-return table (sector data from swing-strategy's own
    // Upstox-fetched sector_candle_cache.json, Nifty 50 benchmark from Yahoo Finance),
    // regenerated by hand every so often rather than refreshed on a schedule. See
    // src/main/resources/dashboard/data/sector-seasonality.json's own "generatedAt".
    private volatile JsonNode seasonalityData;

    public DashboardDataController(AlertLogService alertLogService, GithubJsonStore githubJsonStore,
                                    QuarterlyResultsService quarterlyResultsService,
                                    RsRankLookupService rsRankLookupService,
                                    RsMomentumService rsMomentumService,
                                    SwingSignalService swingSignalService,
                                    SwingLivePriceService swingLivePriceService,
                                    CryptoForexService cryptoForexService) {
        this.alertLogService = alertLogService;
        this.githubJsonStore = githubJsonStore;
        this.quarterlyResultsService = quarterlyResultsService;
        this.rsRankLookupService = rsRankLookupService;
        this.rsMomentumService = rsMomentumService;
        this.swingSignalService = swingSignalService;
        this.swingLivePriceService = swingLivePriceService;
        this.cryptoForexService = cryptoForexService;
    }

    // Swing Strategy tab -- reads swing.signals from Postgres (written by the
    // swing-strategy/live Node service), then attaches a LIVE last price to each
    // OPEN position so `since alert %` tracks the current price instead of the
    // frozen 19:00 snapshot. Same "attach fresh, don't trust the stored snapshot"
    // pattern as RS Rank below. Live prices are cached 60s in SwingLivePriceService,
    // and only fetched during NSE cash-market hours (see isMarketHours) -- outside
    // that window rows simply keep their stored snapshot instead of paying for an
    // Upstox round-trip that can't return anything fresher. Closed rows keep their
    // realized %, pending rows have no entry to price.
    //
    // Also attaches `todayPct` -- the day's move only, distinct from `sinceAlertPct`
    // (the whole-position return). Baseline is the stored `lastPrice` snapshot: the
    // Node runner writes it as "most recent close seen" once per day (19:00 IST,
    // after that day's close), so during the NEXT trading day it's exactly
    // yesterday's close -- the correct denominator for today's move. Must be read
    // before it's overwritten below with the live price.
    //
    // `actionToday` flags rows a trader needs to look at today without scanning the
    // whole list: a brand-new pending signal (plan tomorrow's entry), a +2R half-book,
    // or a full exit -- all detected by comparing the row's date fields to `today`,
    // which is NOT the wall clock -- it's the latest of those same date fields found
    // anywhere in this dataset (see latestSignalDay). The Node runner only stamps a
    // NEW date on an actual trading day's 19:00 run; on a market holiday it still
    // runs, but finds no new close and stamps nothing new, so the data-derived "today"
    // simply doesn't advance and today's badges stay live straight through the
    // holiday -- a wall-clock/19:00 cutoff can't tell a holiday from a trading day,
    // this can, for free, because it only ever moves when the data actually does.
    @GetMapping(value = "/api/dashboard/swing", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<Map<String, Object>> swing() {
        List<Map<String, Object>> rows = swingSignalService.all();
        // The runner only upserts swing.signals, it never deletes -- so rows for a symbol
        // dropped from the halal universe (e.g. the 2026-08-14..19 unscreened-Nifty-500
        // window, see PR #32) stay in Postgres forever with nothing left to age them out.
        // Filter them out here rather than deleting the underlying data.
        rows.removeIf(r -> r.get("symbol") == null || !swingLivePriceService.isInUniverse(r.get("symbol").toString()));
        String today = latestSignalDay(rows);
        List<String> openSymbols = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            if ("open".equals(r.get("status")) && r.get("symbol") != null) openSymbols.add(r.get("symbol").toString());
            boolean actionToday = today != null && (today.equals(r.get("halfDate")) || today.equals(r.get("exitDate"))
                    || ("pending".equals(r.get("status")) && today.equals(r.get("signalDate"))));
            r.put("actionToday", actionToday);
            // Same lookup used by the Quarterly Results card -- current rank, not the
            // rank as of signal date. Unlike Quarterly Results, coverage here is
            // effectively the full swing universe (swing-strategy/live/symbols.json
            // is kept identical to rs-momentum-strategy's own universe) -- a null
            // means insufficient price history (e.g. a recent IPO), not exclusion.
            // See RsRankLookupService's own doc comment.
            if (r.get("symbol") != null) {
                Double rank = rsRankLookupService.rankFor(r.get("symbol").toString());
                if (rank != null) r.put("rsRank", rank);
            }
        }
        if (!openSymbols.isEmpty() && isMarketHours()) {
            Map<String, Double> live = swingLivePriceService.pricesFor(openSymbols);
            for (Map<String, Object> r : rows) {
                if (!"open".equals(r.get("status"))) continue;
                Object symO = r.get("symbol"), entO = r.get("entryPx");
                if (symO == null || !(entO instanceof Number)) continue;
                Double lp = live.get(symO.toString());
                if (lp == null) continue;
                double entry = ((Number) entO).doubleValue();
                if (entry <= 0) continue;
                Object prevCloseO = r.get("lastPrice");
                if (prevCloseO instanceof Number prevClose && prevClose.doubleValue() > 0) {
                    r.put("todayPct", Math.round(((lp - prevClose.doubleValue()) / prevClose.doubleValue()) * 1000.0) / 10.0);
                }
                r.put("lastPrice", lp);
                r.put("sinceAlertPct", Math.round(((lp - entry) / entry) * 1000.0) / 10.0); // 1 dp
            }
        }
        return rows;
    }

    // The most recent date stamped anywhere in this dataset by the Node runner's
    // once-daily 19:00 IST run. The runner (swing-strategy/live/service_pg.js) fires
    // every calendar day with no holiday/weekend check of its own -- but on a day the
    // market didn't trade there's no fresh close to process, so it stamps nothing new.
    // That makes this max, unlike a wall-clock cutoff, naturally holiday-aware: it only
    // advances when a real trading day's run actually wrote a new signalDate/halfDate/
    // exitDate, and otherwise keeps pointing at the last real trading day indefinitely.
    // YYYY-MM-DD strings sort lexicographically == chronologically, so plain
    // String.compareTo is enough. Returns null only if rows is empty.
    private String latestSignalDay(List<Map<String, Object>> rows) {
        String latest = null;
        for (Map<String, Object> r : rows) {
            latest = laterDate(latest, (String) r.get("halfDate"));
            latest = laterDate(latest, (String) r.get("exitDate"));
            if ("pending".equals(r.get("status"))) latest = laterDate(latest, (String) r.get("signalDate"));
        }
        return latest;
    }

    private String laterDate(String a, String b) {
        if (b == null) return a;
        if (a == null) return b;
        return a.compareTo(b) >= 0 ? a : b;
    }

    // NSE cash session: 09:15-15:30 IST, Mon-Fri. Live-price the Swing tab's open
    // positions only inside that window -- outside it Upstox's intraday-candle feed
    // has nothing fresher to give us, so skip the network round-trip and let rows
    // keep their stored (19:00 runner) snapshot.
    private boolean isMarketHours() {
        ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Asia/Kolkata"));
        if (now.getDayOfWeek() == DayOfWeek.SATURDAY || now.getDayOfWeek() == DayOfWeek.SUNDAY) return false;
        LocalTime t = now.toLocalTime();
        return !t.isBefore(LocalTime.of(9, 15)) && !t.isAfter(LocalTime.of(15, 30));
    }

    // Unlike the other 4 tabs, this reads straight from Postgres (this same
    // service) instead of a cross-branch GitHub read -- no cache needed, it's
    // already a fast local query.
    @GetMapping(value = "/api/dashboard/quarterly-results", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<Map<String, Object>> quarterlyResults() {
        List<Map<String, Object>> results = quarterlyResultsService.recentResults(200);
        // RS Rank is attached LIVE here, always overwriting whatever was
        // persisted at announcement-processing time -- unlike revenue/profit/
        // margin/EPS (fixed historical facts about a specific quarter), RS
        // Rank is a day-to-day-changing attribute of the STOCK, not the
        // filing. Storing it once at record time created a real race: any
        // announcement processed before that day's RS-momentum batch run
        // (20:00-20:30 IST) got a permanently frozen null, confirmed live on
        // AWL 2026-07-30 (announced 11:47 UTC, that day's rank snapshot
        // didn't exist until ~11:55 UTC). Same "attach fresh, don't trust the
        // stored snapshot" pattern as attachForwardPerformance below.
        for (Map<String, Object> row : results) {
            Object symbol = row.get("symbol");
            if (symbol != null) row.put("rsRank", rsRankLookupService.rankFor(symbol.toString()));
        }
        return results;
    }

    // Companies whose results PDF/data COULDN'T be parsed -- previously these left no trace
    // anywhere, indistinguishable from "NSE just hasn't announced it yet". See
    // QuarterlyResultsService.recordFailure/clearFailures.
    @GetMapping(value = "/api/dashboard/quarterly-results-failures", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<Map<String, Object>> quarterlyResultsFailures() {
        return quarterlyResultsService.recentFailures(200);
    }

    @GetMapping(value = "/api/dashboard/market-news", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<ObjectNode> marketNews() {
        List<ObjectNode> list = new ArrayList<>(alertLogService.getMarketNews());
        list.sort(Comparator.comparing((ObjectNode n) -> n.path("timestamp").asText("")).reversed());
        return list;
    }

    @GetMapping(value = "/api/dashboard/announcements", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<ObjectNode> announcements() {
        List<ObjectNode> list = new ArrayList<>(alertLogService.getAnnouncements());
        list.sort(Comparator.comparing((ObjectNode n) -> n.path("timestamp").asText("")).reversed());
        return list;
    }

    // Reads rs_momentum_status (Postgres) instead of the old append-only
    // rs_momentum_log.json cross-branch read -- one row per symbol, upserted in place
    // by rs-momentum-strategy-live on every status change, so the same stock no longer
    // piles up duplicate rows across daily runs. See RsMomentumService.
    @GetMapping(value = "/api/dashboard/rs-momentum", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<Map<String, Object>> rsMomentum() {
        List<Map<String, Object>> statuses = rsMomentumService.all();
        // "How did it do after we alerted it" (2026-07-28) -- a per-symbol rollup still
        // computed daily by server.js/forward_performance.js and pushed to the same
        // GitHub branch as before; only the log itself moved off GitHub, not this file.
        JsonNode perf = cachedRead("rs-momentum-perf", "data/rs-momentum-log", "rs-momentum-strategy/live/rs_momentum_forward_performance.json");
        attachForwardPerformanceToMaps(statuses, perf, "returnSinceEntry");
        return statuses;
    }

    @GetMapping(value = "/api/dashboard/multibagger", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<JsonNode> multibagger() {
        // Same fix, same date -- multibagger-screener/git_state.js.
        JsonNode node = cachedRead("multibagger", "data/multibagger-log", "multibagger-screener/forward_performance_log.json");
        List<JsonNode> events = reversedArray(node);
        // Same addition as rsMomentum() above, sourced from
        // multibagger-screener/forward_performance.js's daily computation.
        JsonNode perf = cachedRead("multibagger-perf", "data/multibagger-log", "multibagger-screener/forward_performance_summary.json");
        attachForwardPerformance(events, perf, "returnSinceQualification");
        return events;
    }

    /** Same merge as attachForwardPerformance, for the rs-momentum-status Map rows (Postgres)
     * instead of JsonNode events (GitHub JSON logs) -- kept separate rather than converting
     * Maps to ObjectNode just to share one method. */
    private void attachForwardPerformanceToMaps(List<Map<String, Object>> rows, JsonNode perfArray, String returnFieldName) {
        if (perfArray == null || !perfArray.isArray()) return;
        Map<String, JsonNode> bySymbol = new HashMap<>();
        for (JsonNode row : perfArray) {
            bySymbol.put(row.path("symbol").asText(""), row);
        }
        for (Map<String, Object> row : rows) {
            JsonNode perf = bySymbol.get(String.valueOf(row.get("symbol")));
            if (perf == null) continue;
            if (perf.has("currentPrice") && !perf.get("currentPrice").isNull()) row.put("currentPrice", perf.get("currentPrice").asDouble());
            if (perf.has(returnFieldName) && !perf.get(returnFieldName).isNull()) row.put("returnSinceAlert", perf.get(returnFieldName).asDouble());
        }
    }

    /** Merges a per-symbol forward-performance summary row (currentPrice + the named return field, as "returnSinceAlert") onto every event belonging to that symbol. */
    private void attachForwardPerformance(List<JsonNode> events, JsonNode perfArray, String returnFieldName) {
        if (perfArray == null || !perfArray.isArray()) return;
        Map<String, JsonNode> bySymbol = new HashMap<>();
        for (JsonNode row : perfArray) {
            bySymbol.put(row.path("symbol").asText(""), row);
        }
        for (JsonNode event : events) {
            if (!(event instanceof ObjectNode obj)) continue;
            JsonNode perf = bySymbol.get(obj.path("symbol").asText(""));
            if (perf == null) continue;
            if (perf.has("currentPrice") && !perf.get("currentPrice").isNull()) obj.set("currentPrice", perf.get("currentPrice"));
            if (perf.has(returnFieldName) && !perf.get(returnFieldName).isNull()) obj.set("returnSinceAlert", perf.get(returnFieldName));
        }
    }

    // Seasonality tab -- month-by-year growth % per Nifty sector index, all sectors at
    // once (client picks Absolute or Vs. Nifty 50, and can drill into one sector). Not a
    // TABS-registered alert feed like the other six endpoints (no "count", no home tile,
    // no session dataCache invalidation story to worry about) -- just a static bundled
    // dataset served as-is. Read once and cached in the instance field above; the file
    // itself is small (tens of KB) so re-reading wouldn't be expensive either, but there's
    // no reason to hit the classpath on every request when the content only changes when
    // someone regenerates the file and redeploys.
    @GetMapping(value = "/api/dashboard/seasonality", produces = MediaType.APPLICATION_JSON_VALUE)
    public JsonNode seasonality() throws java.io.IOException {
        JsonNode data = seasonalityData;
        if (data == null) {
            data = mapper.readTree(new ClassPathResource("dashboard/data/sector-seasonality.json").getInputStream());
            seasonalityData = data;
        }
        return data;
    }

    // Crypto/Forex tab -- ALL trades (open + closed) from the Ichimoku BTC/XAU
    // MTF scanner (ichimoku-btc-xau-strategy/live, Node service streaming
    // Pi42), read straight from this same shared Postgres instance. See
    // CryptoForexService's doc comment. Replaced the "Today's DarvasBox" tab
    // (removed 2026-08-22, per the user's request) at this position.
    @GetMapping(value = "/api/dashboard/crypto-forex", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<Map<String, Object>> cryptoForex() {
        return cryptoForexService.allTrades();
    }

    private List<JsonNode> reversedArray(JsonNode node) {
        List<JsonNode> list = new ArrayList<>();
        if (node != null && node.isArray()) {
            for (JsonNode n : node) list.add(n);
        }
        java.util.Collections.reverse(list); // logs are appended chronologically -- newest last -> newest first
        return list;
    }

    private JsonNode cachedRead(String key, String branch, String path) {
        CacheEntry entry = cache.get(key);
        long now = System.currentTimeMillis();
        if (entry != null && now - entry.fetchedAt < CACHE_TTL_MS) return entry.data;
        JsonNode fresh = githubJsonStore.readJson(branch, path);
        cache.put(key, new CacheEntry(fresh, now));
        return fresh;
    }

    private record CacheEntry(JsonNode data, long fetchedAt) {}
}
